name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.25
  UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}

permissions:
  contents: write
  id-token: write  # Required for npmjs OIDC
  discussions: write

jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16  # v6.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make build-all-platforms
      - name: Upload artifacts
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2.6.2
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            LICENSE
            podman-mcp-server-*
      # Ensure npm 11.5.1 or later is installed (required for https://docs.npmjs.com/trusted-publishers)
      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38  # v6.5.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Publish npm
        run:
          make npm-publish
  python:
    name: Release Python
    # Python logic requires the tag/release version to be available from GitHub
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6.1.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7.6.0
      - name: Publish Python
        run:
          make python-publish
